changed icon
developerspoint-org/developerspoint.github.io pull request #37
Opened 2020-11-19 09:12 UTC by prilily

2020-11-19 18:38 UTC, ravijainpro approved these changes

2020-11-19 18:41 UTC, ravijainpro requested changes
Kindly, go to [this link](https://www.favicon-generator.org/) and generate a new set of favicons and replace all the existing ones (There are multiple files with flipped images)

2020-11-22 15:33 UTC, ravijainpro commented
> Kindly, go to [this link](https://www.favicon-generator.org/) and generate a new set of favicons and replace all the existing ones (There are multiple files with flipped images)

@prilily Any updates? Any questions?

2020-11-23 07:47 UTC, LowNightSnack commented
duplicate pull request created #42

2020-11-23 07:47 UTC, closed without merging